services:
  - type: web
    name: snake-io
    env: static
    buildCommand: cd src/frontend/features/dot-collector-game && npm install --legacy-peer-deps && npm run build
    staticPublishPath: src/frontend/features/dot-collector-game/build
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
